# Rosé Pine Dawn tmux colors
set -g status-style 'bg=#286983 fg=#faf4ed'
set -g status-left-style 'bg=#286983 fg=#faf4ed bold'
set -g status-right-style 'bg=#9893a5 fg=#faf4ed'
set -g window-status-style 'bg=#286983 fg=#faf4ed'
set -g window-status-current-style 'bg=#286983 fg=#faf4ed bold'
set -g pane-border-style 'fg=#9893a5'
set -g pane-active-border-style 'fg=#286983'
