local function setup()
  require('p-cpp')
  require('p-css')
  require('p-ts')
  require('p-angular')
  require('p-java')
  require('p-bash')
  require('p-cmake')
  require('p-tex')
  require('p-svl')
  require('p-asm')
  require('p-docker')
  require('p-python')
  require('p-html')
  require('p-arduino')
  require('p-nginx')
  require('p-typst')
  require('p-toml')
  require('p-eslint')
  require('p-go')
  require('p-jq')
  require('p-rust')
  require('p-qt')
  require('p-lua')
  require('p-vue')
  require('p-kotlin')
end
return { setup = setup }
